In [1]:
import matplotlib.pyplot as plt
from tqdm import tqdm, trange
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from bokePolicy import PolicyNet, NinebyNineGames, policy_predict, features, SCALE
import go
%matplotlib inline

In [2]:
data_reg = NinebyNineGames(path = r"/home/meiji163/Documents/BokeGo/data/boards.csv", scale = SCALE)

In [5]:
data_reg[2]

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[2., 2., 2., 2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2., 2., 2., 2.],
          [2., 2., 2., 2., 2., 2.,

In [3]:
SCALE = 100
data_ref = NinebyNineGames(path = r"/home/meiji163/Documents/BokeGo/data/boards.csv", transform = "reflect", scale = SCALE)
data_rot = NinebyNineGames(path = r"/home/meiji163/Documents/BokeGo/data/boards.csv", transform = "rot90", scale = SCALE)

pi = PolicyNet(scale = SCALE)

In [ ]:
g = go.Game()
features(g, transform = "rot90")

In [4]:
print(data_reg[5][0][0], go.unsquash(data_reg[5][1]))
print(data_ref[5][0][0], go.unsquash(data_ref[5][1]))
print(data_rot[5][0][0], go.unsquash(data_rot[5][1]))

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0, 100,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0, 100,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0, 100,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0]]) (2, 4)
tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0, 100,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0, 100,   0, 100,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0]]) (

In [ ]:
import numpy as np
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)
c = np.array([9,10,11,12]).reshape(2,2)
d = np.array([13,14,15,16]).reshape(2,2)
e = np.stack([a,b,c,d])
np.rot90(e, k = 3, axes = (1,2))

In [ ]:

err = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(pi.parameters(), lr = 0.01)
checkpt = torch.load(r"/home/jupyter/BokeGo/policy_train.pt")

In [ ]:
pi.load_state_dict(checkpt["model_state_dict"])
pi.eval()

In [ ]:
optimizer.load_state_dict(checkpt['optimizer_state_dict'])
g = go.Game()
g.play_move(40)
probs, moves = policy_predict(pi, g, device = "cuda")
probs

In [ ]:
type([1,2]) == list

In [ ]:
import numpy as np
import go
M = np.zeros((9,9))

M[1,3] = 1
M[3,4] =1
M[5,6] = 1
print(M)
print(M.T)

def rot90c(sq_c):
    return (9*sq_c + 8 - sq_c//9)%81

def reflect(sq_c):
    x, y = divmod(sq_c, 9)
    return 9*y + x

for t in [(1,3),(3,4),(5,6)]:
    sq_m = go.squash(t)
    res = go.unsquash(reflect(sq_m))
    print(res)
    

In [ ]:
print(go.unsquash(48))
x, y = divmod(48, 9)
go.unsquash(9*y+x) 